Issue290 Make the rectNxM restart files valid again
nextsimhub/nextsimdg pull request #364
Opened 2023-08-16 19:28 UTC by timspainNERSC

# Make the rectNxM restart files valid again
## Fixes \#(290)

---
# Change Description

After changes to the grid and the swap of the array ordering, the `init_rectNxM.nc` are no longer valid. 
---
# Test Description

The fixed files can be verified by the model running the config_rectNxM.cfg configuration files successfully.

2023-08-18 11:49 UTC, timspainNERSC commented
To be merged after #306

2023-08-30 06:06 UTC, einola commented
@timspainNERSC : Can you fix the conflicts on this one and request a review?

2023-09-01 14:05 UTC, a-smith-github requested changes
Review unfinished

But please more comments, especially in tests (thinking ModelArray_test in particular!!!) and notes for reviewers. Can't review effectively without them. Time is valuable. 


Could some of those run scripts be more unified to reduce maintenance?

2023-09-01 14:05 UTC, a-smith-github commented on run/init_topaz128x128.py
> +    hfield_dims = ("y", "x")
ditto / ditto

2023-09-06 09:44 UTC, timspainNERSC commented
PR #380 reflects what this PR will look like after PR #373 is merged into develop.

2023-09-11 13:46 UTC, timspainNERSC commented on core/src/ParaGridIO.cpp
> +        std::reverse(v.begin(), v.end());
Entirely correct to flag this; the dimMap array was being reversed twice.

2023-09-11 13:48 UTC, timspainNERSC commented on core/src/ParaGridIO.cpp
> +            std::reverse(extentVector.begin(), extentVector.end());
Added an extra explanatory comment.

2023-09-22 11:23 UTC, TomMelt approved these changes
Looks good to me.

2023-09-22 13:31 UTC, merged