Documentation for running with MPI
nextsimhub/nextsimdg pull request #493
Opened 2024-02-02 13:05 UTC by MarionBWeinzierl

This PR closes #491 .

While #483 has added information on how to build nextsim with MPI, the information about how to run it was still only present in issues (e.g., #490) .

I have added that info to the "Getting started" part of the documentation, and also added an example partition file to the `run` directory to enable users to run the simple example without having to install the decomp tool.

2024-02-05 15:37 UTC, TomMelt requested changes
Looks good to me. Just a couple of comments to address.

2024-02-05 15:37 UTC, TomMelt commented on docs/getting_started.rst
> +To run the model with MPI you have to have it built with MPI or use the `*_MPI` Dockerfile. In addition, you will need a partition NetCDF file as created by the `Domain Decomposition tool <https://gi
```suggestion
To run the model with MPI you have to have it built with MPI or use one of the `*_MPI` Dockerfiles. In addition, you will need a partition NetCDF file as created by the `Domain Decomposition tool <https://github.com/nextsimhub/domain_decomp>`_. This partition file has to either be added to the config file (`*.cfg`) by adding the line `partition_file = partition.nc` or provided as an argument to `nextsim`.
```

2024-02-05 16:22 UTC, TomMelt commented on run/partition.nc
can we host it on the ftp server instead? or use the `.cdl` format which is plaintext and can be converted to netcdf using `ncgen partition.cdl -o partition.nc`. I have been on a mission to remove binaries from the source code :grimacing: I know it's a small binary but I try to avoid binaries in git as much as possible. Maybe I am being overkill...

2024-02-06 09:48 UTC, MarionBWeinzierl commented on run/partition.nc
OK, I removed the nc file and added a cdl file, including updating the docs with instructions. I also added a partition_metadata_2 file

2024-02-06 09:54 UTC, TomMelt commented on run/partition.nc
that's perfect thank you

2024-02-06 09:55 UTC, TomMelt approved these changes

2024-02-06 09:55 UTC, merged