Wrap XIOS functionality for reading from file
nextsimhub/nextsimdg pull request #597
Opened 2024-06-27 17:48 UTC by jwallwork23

# Wrap XIOS functionality for reading from file
## Fixes \#577

### Task List
- [x] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [ ] Implemented the source code change that satisfies the tests
- [ ] Documented the feature by providing worked example
- [ ] Updated the README or other documentation
- [ ] Completed the pre-Request checklist below

---
# Change Description

So far we have only considered writing to file in the XIOS integration work. This PR will enable reading from file, too, although there seems to be a hitch with completing this right now.

---
# Test Description

A `XiosRead_test.cpp` script is added, which reads from a `input.nc` file and checks its dimensions and values are as expected. To support this, XIOS' read methods are wrapped, as well as methods for setting file attributes related to the file mode (read vs. write) and parallel access mode.

Question for reviewer: is it okay to add a NetCDF file to the repo? (I notice such files are ignored by default so had to force-add it.)

This PR also modifies `XiosFile_test.cpp` to test the newly wrapped parts of the XIOS API related to file attributes, as well as modifying `XiosWrite_test.cpp` to check the existence of `output.nc` and delete it at the end of the test.

---
### Pre-Request Checklist

- [x] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [x] No new warnings are generated
- [x] The documentation has been updated (or an issue has been created to track the corresponding change)
- [x] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [x] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [ ] File dates have been updated to reflect modification date
- [ ] This change conforms to the conventions described in the README

*Please complete your pull request description and delete the instructional text before submitting.*

*Congratulations and thank you for making your contribution to neXtSIM_DG!*

2024-06-27 17:50 UTC, jwallwork23 commented on core/test/XiosRead_test.cpp
> +        xios_handler.read("field_4D", field_4D, n1, n2, n3, n4);
This doesn't currently work. I'm getting the error:
```
In file "nc4_data_input.cpp", function "virtual void xios::CNc4DataInput::readFieldAttributes_(xios::CField*, bool)",  line 171 -> Field 'field_2D' has incorrect dimension 
Verify dimension of grid defined by 'grid_ref' or 'domain_ref'/'axis_ref' and dimension of grid in read file.
```

2024-07-17 12:53 UTC, jwallwork23 commented on core/test/XiosRead_test.cpp
> +        xios_handler.read("field_4D", field_4D, n1, n2, n3, n4);
The issue was a bug in XIOS for the case where the grid is built only from axes (not a domain). One of the developers provided a fix for this, so I just need to update the Docker build to use latest XIOS.

2024-07-24 16:21 UTC, jwallwork23 commented on core/test/XiosRead_test.cpp
> +        xios_handler.read("field_4D", field_4D, n1, n2, n3, n4);
This has now been done.

2024-07-25 06:41 UTC, timspainNERSC commented on core/test/input.nc
Rather than having a binary netCDF file in the repo, would it be possible to have a netCDF CDL and to have CMake  run `ncgen` at build time? This is my goal for the remaining binary netCDF files in the repo (but I haven't got to doing it yet).

2024-07-25 06:45 UTC, timspainNERSC requested changes
All the code looks good, but I'd rather we avoided adding another binary netCDF file to the repo.

2024-07-25 06:46 UTC, jwallwork23 commented on core/test/input.nc
Sure, will take a look at setting that up.

2024-07-25 08:18 UTC, TomMelt commented on core/test/input.nc
FYI, there's an example here:
https://github.com/nextsimhub/nextsimdg/blob/eda8b74f5fae8a6a97d4133219a28c883b864973/core/test/CMakeLists.txt#L23-L31

The CDL file is generated by running something like:
```
ncdump mynetcdffile.nc > myCDLfile.cdl
```

2024-07-25 08:20 UTC, TomMelt commented on core/test/input.nc
The first person to commit a CDL file to the repo used the extension `.nc.dump` (so in my branch I followed this scheme) but I would actually prefer if we move all of them to `.cdl`

@timspainNERSC  would you agree?

2024-07-25 08:22 UTC, timspainNERSC commented on core/test/input.nc
> The first person to commit a CDL file to the repo used the extension `.nc.dump` (so in my branch I followed this scheme) but I would actually prefer if we move all of them to `.cdl`
> 
> @timspainNERSC would you agree?

Absolutely yes!

2024-07-25 08:23 UTC, TomMelt commented on core/test/input.nc
@jwallwork23 , is it possible to do a bit of `git rebase` magic to make sure the commits containing  netcdf binary files dont end up in the repo? 

I am not sure if this is completely necessary, so ignore me if it's too difficult. Another solution is we could just squash the commits? :shrug:

2024-07-25 08:27 UTC, TomMelt requested changes
Thanks @jwallwork23 , this looks great. I approve pending the removal of the netcdf file.

2024-07-25 09:00 UTC, jwallwork23 commented on core/test/input.nc
Tbh rebase would be a headache, how about we squash merge?

2024-07-25 09:14 UTC, jwallwork23 commented
The commit history is rather nonlinear given a couple of merges from `develop` so (as mentioned above) I advocate squash-merging this PR rather than going through a rebase.

2024-07-26 07:58 UTC, TomMelt commented on core/test/input.nc
Yeah squash merge sounds sensible

2024-07-30 09:26 UTC, TomMelt approved these changes
Thanks for changing the netcdf files

2024-08-05 09:22 UTC, jwallwork23 commented
This has now been updated to use CDL files rather than NetCDF. Would you mind taking a look to re-review @timspainNERSC?

2024-08-05 11:10 UTC, timspainNERSC requested changes
Looks good, except for the discussion we are about to have _re_ initialization methods

2024-08-05 11:23 UTC, jwallwork23 commented on core/test/XiosField_test.cpp
> +    const std::string gridRef = { "grid_1D" };
Thanks. This will be fixed in #635.

2024-08-21 08:34 UTC, timspainNERSC approved these changes
Looks good.

2024-08-21 08:37 UTC, merged