Drop XIOS `isDefined*` and `areDefined*` methods
nextsimhub/nextsimdg pull request #630
Opened 2024-07-29 09:24 UTC by jwallwork23

# Drop XIOS `isDefined*` and `areDefined*` methods
## Fixes #629

### Task List
- [x] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [x] Implemented the source code change that satisfies the tests
- [x] Documented the feature by providing worked example
- [x] Updated the README or other documentation
- [x] Completed the pre-Request checklist below

---
# Change Description

It's unnecessary for us to provide API functions for checking whether XIOS attributes are defined. We can cut down API size, implement self-testing code, and reduce verbosity by just inlining the associated XIOS functions within the getter and setter methods.

---
### Pre-Request Checklist

- [x] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [x] No new warnings are generated
- [x] The documentation has been updated (or an issue has been created to track the corresponding change)
- [x] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [x] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [x] File dates have been updated to reflect modification date
- [x] This change conforms to the conventions described in the README

2024-07-31 14:40 UTC, timspainNERSC requested changes
Looks good, except for my comment on the contents of some of the error messages (if I am understanding correctly).

2024-07-31 14:40 UTC, timspainNERSC commented on core/src/Xios.cpp
I'm a bit unclear on whether all the mentions of longitude and latitude actually refer to those global coordinates. It looks like some errors in setting the size of the i and j dimensions would result in errors referring to longitude or latitude. In the case where we are running a regional model domain (like the Arctic domain I usually test on), this might be confusing. Conversely, some of the mentions of longitude in the error messages do seem to be referring to errors in setting the values of the geographical coordinate.
Could you make sure that wherever longitude or latitude are mentioned in the error messages, that is really what is being referred to?

2024-08-01 08:08 UTC, jwallwork23 commented on core/src/Xios.cpp
Ah yes, thanks for pointing this out @timspainNERSC. I've checked over the domain methods and think I addressed the issue in my latest commit. Would it be useful to use the naming pattern `setDomainLocalLatitude` etc., to more clearly differentiate between the local and global versions?

2024-08-01 08:36 UTC, jwallwork23 commented on core/src/Xios.cpp
Thanks for the elaboration. I think XIOS uses the terms latitude and longitude because until recently it's always been used on lat-long grids. But yes, we can certainly using different names. In addition to reworking the error messages, it's probably a good opportunity to switch to more appropriate names for the methods, too. How about the following patterns?
```
setDomainLocalXSize(...)
getDomainGlobalYValues(...)
```

2024-08-01 08:38 UTC, timspainNERSC commented on core/src/Xios.cpp
> Thanks for the elaboration. I think XIOS uses the terms latitude and longitude because until recently it's always been used on lat-long grids. But yes, we can certainly using different names. In addition to reworking the error messages, it's probably a good opportunity to switch to more appropriate names for the methods, too. How about the following patterns?
> 
> ```
> setDomainLocalXSize(...)
> getDomainGlobalYValues(...)
> ```

I'm definitely in favour of that.

2024-08-01 09:50 UTC, jwallwork23 commented on core/src/Xios.cpp
Okay I've now updated all the names, docstrings, and error messages/warnings. Hopefully clearer now. I also made one minor reordering for consistency.

2024-08-01 13:43 UTC, timspainNERSC approved these changes
That all looks good now

2024-08-01 13:55 UTC, jwallwork23 commented
Thanks @timspainNERSC

2024-08-01 13:56 UTC, merged